version: '3.9'
services:
  template-typescript:
    container_name: template-typescript
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file: .env